应用了B站网友的建议
Teahouse-Studios/mcwzh-meme-resourcepack-bedrock pull request #23
Opened 2021-08-13 13:42 UTC by RxinnotRstar

### 来源
https://github.com/Teahouse-Studios/mcwzh-meme-resourcepack/issues/191

2021-08-13 13:46 UTC, Dianliang233 commented
为什么删掉了译名修正？

2021-08-13 13:48 UTC, RxinnotRstar commented
> 
> 
> 为什么删掉了译名修正？

WHAT

没有啊，难道我误删了？

2021-08-13 13:49 UTC, lakejason0 commented
译名修正是本资源包附带的功能，也是为了维护方便。请不要删除`zh-cn.lang`。

2021-08-13 13:50 UTC, RxinnotRstar commented
> 
> 
> 译名修正是本附加包的**功能**，也是为了维护方便。请不要删除`zh_CN.lang`。

误删了，现在补……

2021-08-13 13:50 UTC, Dianliang233 requested changes

2021-08-13 13:50 UTC, Dianliang233 commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=看了博人传的火然起来了的珊瑚块	#
typo

2021-08-13 13:54 UTC, Dianliang233 commented
操作暂未决定。等待 Teahouse-Studios/mcwzh-meme-resourcepack#191。

2021-08-13 14:00 UTC, RxinnotRstar commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=看了博人传的火然起来了的珊瑚块	#
> 
> 
> typo

没看见有typo啊……

2021-08-13 14:02 UTC, lakejason0 commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=看了博人传的火然起来了的珊瑚块	#
然
难不成你要然然你的然然？

2021-08-13 14:05 UTC, RxinnotRstar commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=看了博人传的火然起来了的珊瑚块	#
> 
> 
> 然
> 难不成你要然然你的然然？

这是把”燃“拆开了，参见原issues.
怎么哪里都有嘉心糖（恼

2021-08-13 14:06 UTC, lakejason0 commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=看了博人传的火然起来了的珊瑚块	#
> 这是把”燃“拆开了
你要不再读一下？

2021-08-13 14:06 UTC, lakejason0 commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=看了博人传的火然起来了的珊瑚块	#
emm

2021-08-13 14:06 UTC, lakejason0 commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=看了博人传的火然起来了的珊瑚块	#
那你把的删掉啊

2021-08-13 14:07 UTC, RxinnotRstar commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=看了博人传的火然起来了的珊瑚块	#
> 
> 
> > 这是把”燃“拆开了
> 
> 你要不再读一下？

这是原提建议者的问题（
那我改一改……

2021-08-21 07:06 UTC, SkyEye-FAST requested changes

2021-08-21 07:06 UTC, SkyEye-FAST commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=火然起来了的珊瑚块看了《博人传》，这是它身体的变化	#
虽然能看出是Chubbyemu的梗，但是其他的死珊瑚块该如何统一进行梗化？

2021-08-21 07:07 UTC, lakejason0 commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=火然起来了的珊瑚块看了《博人传》，这是它身体的变化	#
It's just not needed to make everything consistent...

2021-09-07 07:01 UTC, RxinnotRstar commented on meme_resourcepack/texts/zh_ME.lang
> +tile.coral_block.red_dead.name=火然起来了的珊瑚块看了《博人传》，这是它身体的变化	#
> 
> 
> 虽然能看出是Chubbyemu的梗，但是其他的死珊瑚块该如何统一进行梗化？

没必要强行统一，就好像“法国国旗”一样（好吧，我知道这个比喻似乎不是很恰当……）

2022-02-03 15:11 UTC, SkyEye-FAST commented
不活跃，若有必要请reopen。
（这玩意怎么能咕这么久
见Teahouse-Studios/mcwzh-meme-resourcepack#191

2022-02-03 15:11 UTC, closed without merging